spring.application.name=ducdeptrai
server.port=8080
spring.datasource.url=jdbc:sqlserver://den1.mssql8.gear.host;encrypt=true;trustServerCertificate=true;databaseName=schoolmanager3
spring.datasource.username=schoolmanager3
spring.datasource.password=Qt4n4gV-W23_
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false